import Head from 'next/head'
import Navbar from "../components/Navbar";
import {minifyRecord, todoTable} from "../utils/Airtable";
import {Todo} from "../components/Todo";
import {TodosContext} from "../contexts/TodosContext";
import {useContext, useEffect} from "react";
import {getSession, useUser, withPageAuthRequired} from "@auth0/nextjs-auth0";
import {TodoForm} from "../components/TodoForm";

export default function Home({initialTodos, initialUser, errorMessage}) {
    const {todos, setTodos} = useContext(TodosContext)
    const {user} = useUser()
    useEffect(() => {
        setTodos(initialTodos)
    }, [setTodos, initialTodos])
    console.log("home", todos)
    const res = (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navbar/>

            <main>
                {user && <>
                    <h1 className="text-2xl text-center mb-4">My Todos</h1>
                    <TodoForm/>
                    <ul>
                        {todos && todos.map(todo => <Todo key={todo.id} todo={todo}/>)}
                    </ul>
                </>}
            </main>
        </div>
    )
    return res
}

export const getServerSideProps = async (ctx) => {
    try {
        const session = getSession(ctx.req, ctx.res)
        let todos = [];
        if (session?.user) {
            todos = await todoTable.select({
                filterByFormula: `userId = '${session.user.sub}'`
            }).firstPage()
        }

        return {
            props: {
                initialUser: session?.user || null,
                initialTodos: todos.map(minifyRecord),
            }
        }
    } catch (err) {
        console.error(err)
        return {
            props: {
                errorMessage: "Something went wrong"
            }
        }
    }
}